name: Code Formatter (Ruff)

on: [push, workflow_dispatch]

jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
          
      - name: Install ruff
        run: pip install ruff
        
      - name: Run ruff
        run: |
          # Formats code (replaces black and isort)
          ruff format .
          # Fixes errors and removes unused imports (replaces autoflake)
          ruff check . --fix
          
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto: Code Formatted [skip ci]"
          commit_options: "--signoff"
          repository: .
          commit_user_name: AnshumanPM
          commit_user_email: anshumanprasadmahanta@gmail.com
          commit_author: AnshumanPM <anshumanprasadmahanta@gmail.com>
          
